# Configuratia Spring Boot (conexiunea la baza de date si portul serverului)
spring.application.name=veterinary-backend

# Conectarea catre serverul MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/veterinar_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Instructiuni pentru Hibernate (ORM) pt. crearea/actualizarea tabelelor SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Setarea portului Backend-ului
server.port=8080
